import React, { useState, useEffect, useRef, useContext, useMemo } from 'react';
import {
  Input,
  ListGroup,
  ListGroupItem,
  Spinner,
} from 'reactstrap';
import { ThemeContext, themes } from "contexts/ThemeContext";
import { t } from "translations/translate";

// Import school data from local JSON file
// This file is generated by scripts/update_schools.py
import schoolData from "../../assets/schools.json";

/**
 * SchoolSearchSelect - A reusable component for searching and selecting Czech schools
 * 
 * DATA SOURCE:
 * ------------
 * The component uses data from `src/data/schools.json` which is generated by 
 * the `scripts/update_schools.py` script. The script downloads and processes
 * the official MŠMT school registry (Rejstřík škol a školských zařízení).
 * 
 * To update the school data, run:
 *   cd scripts && python3 update_schools.py
 * 
 * EXPECTED DATA STRUCTURE (schools.json):
 * ---------------------------------------
 * {
 *   "generatedAt": "2026-01-21T12:00:00Z",  // When the data was generated
 *   "sourceDate": "2026-01-21",              // Date of the MŠMT source data
 *   "totalCount": 9987,                      // Total number of schools
 *   "schools": [
 *     {
 *       "name": "Základní škola, Praha 1, Vodičkova 22",   // Full official name
 *       "shortName": "ZŠ Vodičkova",                        // Short name (optional)
 *       "address": "Ostrovní 139/11, Praha 1",             // Full address
 *       "city": "Praha 1"                                   // City/district only
 *     },
 *     ...
 *   ]
 * }
 * 
 * SOURCE DATA FORMAT (MŠMT RSSZ JSONLD):
 * --------------------------------------
 * The script processes data from:
 * https://lkod-ftp.msmt.gov.cz/00022985/88a7c12b-6084-4e47-8b50-46097c6e683f/RSSZ-cela-CR.jsonld
 * 
 * Each school record in source contains:
 * - redIzo: Unique school identifier
 * - uplnyNazev: Full official name
 * - zkracenyNazev: Short name
 * - adresa: Address object with ulice, cisloDomovni, obec, cisloObvoduPrahy, etc.
 * 
 * Props:
 * ------
 * - value: string - Current school name value
 * - onChange: (schoolName) => void - Callback when school name changes
 * - placeholder: string - Placeholder text for the input
 * - disabled: boolean - Whether the component is disabled
 * - invalid: boolean - Whether the input is in invalid state
 * - clearable: boolean - Whether to show a clear button when there's a value
 */
function SchoolSearchSelect({
  value = '',
  onChange,
  placeholder = null,
  disabled = false,
  invalid = false,
  clearable = false,
}) {
  const [searchTerm, setSearchTerm] = useState(value || '');
  const [results, setResults] = useState([]);
  const [showResults, setShowResults] = useState(false);
  const [isFocused, setIsFocused] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  
  const wrapperRef = useRef(null);
  const debounceRef = useRef(null);
  
  const { theme } = useContext(ThemeContext);
  const isDark = theme === themes.dark;
  
  // Theme-aware colors
  const dropdownBg = isDark ? '#1e1e2f' : '#ffffff';
  const dropdownBorder = isDark ? '#2b3553' : '#e3e3e3';
  const textColor = isDark ? '#fff' : '#344675';
  const hoverBg = isDark ? '#2b3553' : '#f8f9fa';

  // Normalize string - remove diacritics and convert to lowercase
  const normalizeString = (str) => {
    if (!str) return '';
    return str
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '') // Remove diacritics
      .replace(/[^a-z0-9\s]/g, ' ') // Replace special chars with space
      .replace(/\s+/g, ' ') // Collapse multiple spaces
      .trim();
  };

  // Sanitize school name input - remove potentially dangerous characters
  const sanitizeSchoolName = (str) => {
    if (!str) return '';
    return str
      .replace(/<[^>]*>/g, '') // Remove HTML tags
      .replace(/[<>"'`\\]/g, '') // Remove dangerous characters
      .replace(/javascript:/gi, '') // Remove javascript: protocol
      .replace(/on\w+=/gi, '') // Remove event handlers like onclick=
      .substring(0, 200); // Limit length - no trim here to allow typing spaces
  };

  // Pre-process schools for faster searching
  // Create searchable strings with name, short name, and city
  const searchableSchools = useMemo(() => {
    if (!schoolData?.schools) return [];
    
    return schoolData.schools.map(school => ({
      ...school,
      // Display string: "Name, City" or just "Name" if no city
      display: school.city ? `${school.name}, ${school.city}` : school.name,
      // Searchable string (normalized - no diacritics, lowercase)
      searchable: normalizeString([
        school.name,
        school.shortName,
        school.city,
        school.address
      ].filter(Boolean).join(' '))
    }));
  }, []);

  // Sync with external value changes
  useEffect(() => {
    if (value !== searchTerm && !isFocused) {
      setSearchTerm(value || '');
    }
  }, [value]);

  // Click outside handler - close dropdown
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (wrapperRef.current && !wrapperRef.current.contains(event.target)) {
        setShowResults(false);
        setIsFocused(false);
      }
    };
    
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (debounceRef.current) {
        clearTimeout(debounceRef.current);
      }
    };
  }, []);

  // Search schools locally
  const searchSchools = (term) => {
    if (!term || term.length < 2) {
      return [];
    }

    const searchNormalized = normalizeString(term);
    const searchWords = searchNormalized.split(/\s+/).filter(w => w.length > 0);
    
    // Find matching schools
    const matches = searchableSchools
      .filter(school => {
        // All search words must be found in the searchable string
        return searchWords.every(word => school.searchable.includes(word));
      })
      .slice(0, 20); // Limit results
    
    return matches.map(school => school.display);
  };

  // Perform search with debounce
  const performSearch = (term) => {
    if (term.length < 2) {
      setResults([]);
      return;
    }

    setIsLoading(true);
    
    // Use requestAnimationFrame for smooth UI
    requestAnimationFrame(() => {
      const searchResults = searchSchools(term);
      setResults(searchResults);
      setIsLoading(false);
    });
  };

  // Debounced search
  useEffect(() => {
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
    }
    
    debounceRef.current = setTimeout(() => {
      if (isFocused && searchTerm.length >= 2) {
        performSearch(searchTerm);
      } else if (searchTerm.length < 2) {
        setResults([]);
      }
    }, 150); // Faster debounce since search is local
    
    return () => {
      if (debounceRef.current) {
        clearTimeout(debounceRef.current);
      }
    };
  }, [searchTerm, isFocused]);

  const handleSelect = (school) => {
    setSearchTerm(school);
    onChange(school);
    setShowResults(false);
    setIsFocused(false);
  };

  const handleInputChange = (e) => {
    const newValue = sanitizeSchoolName(e.target.value);
    setSearchTerm(newValue);
    onChange(newValue);
    setShowResults(true);
  };

  const handleFocus = () => {
    setIsFocused(true);
    setShowResults(true);
    if (searchTerm.length >= 2) {
      performSearch(searchTerm);
    }
  };

  const handleBlur = () => {
    // Delay to allow click on dropdown item
    setTimeout(() => {
      if (wrapperRef.current && !wrapperRef.current.contains(document.activeElement)) {
        setShowResults(false);
        setIsFocused(false);
      }
    }, 150);
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Escape') {
      setShowResults(false);
    }
  };

  const handleClear = () => {
    setSearchTerm('');
    onChange('');
    setResults([]);
    setShowResults(false);
  };

  return (
    <div 
      ref={wrapperRef} 
      style={{ position: 'relative' }}
    >
      <Input
        type="text"
        value={searchTerm}
        onChange={handleInputChange}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
        placeholder={placeholder || t("enterSchoolName")}
        disabled={disabled}
        invalid={invalid}
        style={{ 
          color: isDark ? 'white' : 'black',
          backgroundColor: isDark ? 'transparent' : 'white',
          paddingRight: clearable && searchTerm ? '35px' : undefined
        }}
        autoComplete="off"
      />
      
      {/* Clear button */}
      {clearable && searchTerm && !disabled && (
        <span
          onClick={handleClear}
          style={{
            position: 'absolute',
            right: '10px',
            top: '50%',
            transform: 'translateY(-50%)',
            cursor: 'pointer',
            color: isDark ? '#8898aa' : '#adb5bd',
            fontSize: '14px',
            zIndex: 5,
            lineHeight: 1
          }}
          title={t("clear") || "Vymazat"}
        >
          <i className="tim-icons icon-simple-remove" />
        </span>
      )}
      
      {/* Loading indicator */}
      {showResults && isLoading && (
        <ListGroup
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            right: 0,
            zIndex: 1050,
            backgroundColor: dropdownBg,
            border: `1px solid ${dropdownBorder}`,
            borderRadius: '0 0 4px 4px',
            boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
            marginTop: '-1px'
          }}
        >
          <ListGroupItem
            style={{
              backgroundColor: dropdownBg,
              color: textColor,
              border: 'none',
              padding: '10px 15px',
              fontSize: '14px',
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
            }}
          >
            <Spinner size="sm" color="primary" />
            {t("searchingSchools") || "Vyhledávám školy..."}
          </ListGroupItem>
        </ListGroup>
      )}

      {/* Results dropdown */}
      {showResults && !isLoading && results.length > 0 && (
        <ListGroup
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            right: 0,
            zIndex: 1050,
            maxHeight: '180px',
            overflowY: 'auto',
            backgroundColor: dropdownBg,
            border: `1px solid ${dropdownBorder}`,
            borderRadius: '0 0 4px 4px',
            boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
            marginTop: '-1px'
          }}
        >
          {results.map((school, index) => (
            <ListGroupItem
              key={index}
              action
              onClick={() => handleSelect(school)}
              style={{
                backgroundColor: dropdownBg,
                color: textColor,
                border: 'none',
                borderBottom: index < results.length - 1 ? `1px solid ${dropdownBorder}` : 'none',
                padding: '10px 15px',
                cursor: 'pointer',
                fontSize: '14px',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = hoverBg;
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = dropdownBg;
              }}
            >
              <i className="tim-icons icon-bank mr-2" style={{ fontSize: '12px', opacity: 0.7 }} />
              {school}
            </ListGroupItem>
          ))}
        </ListGroup>
      )}
      
      {/* No results */}
      {showResults && !isLoading && results.length === 0 && searchTerm.length >= 2 && (
        <ListGroup
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            right: 0,
            zIndex: 1050,
            backgroundColor: dropdownBg,
            border: `1px solid ${dropdownBorder}`,
            borderRadius: '0 0 4px 4px',
            boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
            marginTop: '-1px'
          }}
        >
          <ListGroupItem
            style={{
              backgroundColor: dropdownBg,
              color: textColor,
              border: 'none',
              padding: '10px 15px',
              fontSize: '14px',
              opacity: 0.7,
            }}
          >
            <i className="tim-icons icon-alert-circle-exc mr-2" style={{ fontSize: '12px' }} />
            {t("noSchoolsFound") || "Škola nenalezena - můžete zadat vlastní název"}
          </ListGroupItem>
        </ListGroup>
      )}

      {/* Hint when typing but not enough characters */}
      {showResults && !isLoading && searchTerm.length > 0 && searchTerm.length < 2 && (
        <ListGroup
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            right: 0,
            zIndex: 1050,
            backgroundColor: dropdownBg,
            border: `1px solid ${dropdownBorder}`,
            borderRadius: '0 0 4px 4px',
            boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
            marginTop: '-1px'
          }}
        >
          <ListGroupItem
            style={{
              backgroundColor: dropdownBg,
              color: textColor,
              border: 'none',
              padding: '10px 15px',
              fontSize: '14px',
              opacity: 0.7,
            }}
          >
            <i className="tim-icons icon-zoom-split mr-2" style={{ fontSize: '12px' }} />
            {t("typeToSearchSchools") || "Zadejte alespoň 2 znaky pro vyhledání"}
          </ListGroupItem>
        </ListGroup>
      )}
    </div>
  );
}

export default SchoolSearchSelect;
